export default {
  login: 'hamid2117',
  id: 68191124,
  node_id: 'MDQ6VXNlcjY4MTkxMTI0',
  avatar_url: 'https://avatars.githubusercontent.com/u/68191124?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/hamid2117',
  html_url: 'https://github.com/hamid2117',
  followers_url: 'https://api.github.com/users/hamid2117/followers',
  following_url:
    'https://api.github.com/users/hamid2117/following{/other_user}',
  gists_url: 'https://api.github.com/users/hamid2117/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/hamid2117/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/hamid2117/subscriptions',
  organizations_url: 'https://api.github.com/users/hamid2117/orgs',
  repos_url: 'https://api.github.com/users/hamid2117/repos',
  events_url: 'https://api.github.com/users/hamid2117/events{/privacy}',
  received_events_url: 'https://api.github.com/users/hamid2117/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 1,
  following: 4,
  created_at: '2020-07-12T13:47:13Z',
  updated_at: '2021-02-28T23:50:43Z',
}
